---
version: '3.7'

services:
  neo4j:
    image: neo4j:${NEO4J_VERSION:-3.5.15-enterprise}
    # depends_on:
    #  - plugins-neo4j
    restart: unless-stopped
    volumes:
      - neo4j_data:/data
    env_file: ".env.neo4j.${RUN_ENV}"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=\*.\*
        #- NEO4J_apoc_import_file_enabled=true
        #- NEO4J_apoc_export_file_enabled=true
      # used to be : NEO4J_dbms_allow__format__migration=true
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_https_advertised__address=neo4j.${TRAEFIK_HOST}:443
      - NEO4J_dbms_connector_bolt_advertised__address=neo4jdb.${TRAEFIK_HOST}:443
    ports:
      - "7473:7473"  # https
      - "7474:7474"  # http
      - "7687:7687"  # bolt
    labels:
      - "traefik.docker.network=traefik_network"
      - "traefik.enable=true"
      - "traefik.http.services.neo4j-secure.loadbalancer.server.port=7474"
      - "traefik.http.routers.neo4j-secure.service=neo4j-secure"
      - "traefik.http.routers.neo4j-secure.entrypoints=https"
      - "traefik.http.routers.neo4j-secure.rule=Host(`neo4j.${TRAEFIK_HOST}`)"
      - traefik.http.routers.neo4j-secure.tls.certresolver=gandi-cr
        # - "traefik.http.services.neo4jdb-secure.loadbalancer.server.port=7687"
        # - "traefik.http.routers.neo4jdb-secure.service=neo4jdb-secure"
        # - "traefik.http.routers.neo4jdb-secure.entrypoints=https"
        # - "traefik.http.routers.neo4jdb-secure.rule=Host(`neo4jdb.${TRAEFIK_HOST}`)"
      - traefik.tcp.services.neo4jdb.loadbalancer.server.port=7687
      - traefik.tcp.routers.neo4jdb.rule=HostSNI(`neo4jdb.${TRAEFIK_HOST}`)
      - traefik.tcp.routers.neo4jdb.service=neo4jdb
      - traefik.tcp.routers.neo4jdb.tls=true
      - traefik.tcp.routers.neo4jdb.tls.certresolver=gandi-cr
    networks:
      - traefik_network

volumes:
  neo4j_data:

networks:
  traefik_network:
    external: true
