---
version: '3.7'

services:
  neo4j:
    image: neo4j:4.4.12-enterprise
    # depends_on:
    #  - plugins-neo4j
    restart: unless-stopped
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=\*.\*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_memory_heap_initial__size=256M
      - NEO4J_dbms_memory_heap_max__size=512M
      - NEO4J_dbms_memory_pagecache_size=512M
      # used to be : NEO4J_dbms_allow__format__migration=true
      - NEO4J_dbms_allow__upgrade=true
      # force password, otherwise neo4j/neo4j and will request reset
      - NEO4J_AUTH=neo4j/neo3j
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_https_advertised__address=neo4j.${TRAEFIK_HOST}:443
      - NEO4J_dbms_connector_bolt_advertised__address=neo4jbolt.${TRAEFIK_HOST}:443
    ports:
      - "7473:7473"  # https
      - "7474:7474"  # http
      - "7687:7687"  # bolt
    labels:
      - "traefik.docker.network=traefik_network"
      - "traefik.enable=true"
      - "traefik.http.services.neo4j-secure.loadbalancer.server.port=7474"
      - "traefik.http.routers.neo4j-secure.service=neo4j-secure"
      - "traefik.http.routers.neo4j-secure.entrypoints=https"
      - "traefik.http.routers.neo4j-secure.rule=Host(`neo4j.${TRAEFIK_HOST}`)"
      - traefik.http.routers.neo4j-secure.tls.certresolver=gandi-cr
        # - "traefik.http.services.neo4jbolt-secure.loadbalancer.server.port=7687"
        # - "traefik.http.routers.neo4jbolt-secure.service=neo4jbolt-secure"
        # - "traefik.http.routers.neo4jbolt-secure.entrypoints=https"
        # - "traefik.http.routers.neo4jbolt-secure.rule=Host(`neo4jbolt.${TRAEFIK_HOST}`)"
      - traefik.tcp.services.neo4jbolt.loadbalancer.server.port=7687
      - traefik.tcp.routers.neo4jbolt.rule=HostSNI(`neo4jbolt.${TRAEFIK_HOST}`)
      - traefik.tcp.routers.neo4jbolt.service=neo4jbolt
      - traefik.tcp.routers.neo4jbolt.tls=true
      - traefik.tcp.routers.neo4jbolt.tls.certresolver=gandi-cr
    networks:
      - traefik_network

volumes:
  neo4j_data:

networks:
  traefik_network:
    external: true
