---
version: '3.7'

services:
  neo4j01:
    hostname: neo4j
    environment:
    - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j01_data:/data
      - neo4j01_datasets:/datasets:ro
      - ./backups:/backups
      # - ./plugins:/plugins
      # - ./scripts:/scripts
    ports:
      - "7473:7473"  # https
      - "7474:7474"  # http
      - "7687:7687"  # bolt

volumes:
  neo4j01_data:
  neo4j01_datasets:
  neo4j02_data:
  neo4j02_datasets:
  neo4j03_data:
  neo4j03_datasets:
