---
version: '3.7'

services:
  neo4j:
    image: neo4j:${NEO4J_VERSION:-4.2.0-enterprise}
    # depends_on:
    #  - plugins-neo4j
    restart: unless-stopped
    env_file: ".env.neo4j.${RUN_ENV}"
    user: "${NEO4J_USER:-7474}:${NEO4J_GROUP:-7474}"
    environment:
      #- NEO4J_dbms_security_procedures_unrestricted=\*.\*
      - NEO4J_dbms_security_procedures_unrestricted=apoc.\*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_trigger_enabled=true
      # used to be : NEO4J_dbms_allow__format__migration=true
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_https_advertised__address=${PREFIX}neo4j.${TRAEFIK_HOST}:443
      - NEO4J_dbms_connector_bolt_advertised__address=${PREFIX}neo4jbolt.${TRAEFIK_HOST}:443
      - NEO4J_metrics_csv_enabled=false
      - NEO4J_metrics_prometheus_enabled=true
      - NEO4J_metrics_prometheus_endpoint=0.0.0.0:2004
      - NEO4J_metrics_namespaces_enabled=true
      - NEO4J_metrics_filter="*bolt.connections*,*bolt.messages_received*,*bolt.messages_started*,*dbms.pool.bolt.free,*dbms.pool.bolt.total_size,*dbms.pool.bolt.total_used,*dbms.pool.bolt.used_heap,*causal_clustering.core.is_leader,*causal_clustering.core.last_leader_message,*causal_clustering.core.replication_attempt,*causal_clustering.core.replication_fail,*check_point.duration,*check_point.total_time,*cypher.replan_events,*ids_in_use.node,*ids_in_use.property,*ids_in_use.relationship,*pool.transaction.*.total_used,*pool.transaction.*.used_heap,*pool.transaction.*.used_native,*store.size*,*transaction.active_read,*transaction.active_write,*transaction.committed*,*transaction.last_committed_tx_id,*transaction.peak_concurrent,*transaction.*,*page_cache.*,*vm.*,"

    labels:
      - "traefik.docker.network=traefik_network"
      - "traefik.enable=true"
      - "traefik.http.services.neo4j${PREFIX}secure.loadbalancer.server.port=7474"
      - "traefik.http.routers.neo4j${PREFIX}secure.service=neo4j${PREFIX}secure"
      - "traefik.http.routers.neo4j${PREFIX}secure.entrypoints=https,https_priv"
      - "traefik.http.routers.neo4j${PREFIX}secure.rule=Host(`${PREFIX}neo4j.${TRAEFIK_HOST}`)"
      - traefik.http.routers.neo4j${PREFIX}secure.tls.certresolver=gandi-cr
      - traefik.tcp.services.neo4j${PREFIX}bolt.loadbalancer.server.port=7687
      - traefik.tcp.routers.neo4j${PREFIX}bolt.rule=HostSNI(`${PREFIX}neo4jbolt.${TRAEFIK_HOST}`)
      - traefik.tcp.routers.neo4j${PREFIX}bolt.service=neo4j${PREFIX}bolt
      - traefik.tcp.routers.neo4j${PREFIX}bolt.tls=true
      - traefik.tcp.routers.neo4j${PREFIX}bolt.tls.certresolver=gandi-cr
      - "traefik.http.services.neo4j${PREFIX}metrics-secure.loadbalancer.server.port=2004"
      - "traefik.http.routers.neo4j${PREFIX}metrics-secure.service=neo4j${PREFIX}metrics-secure"
      - "traefik.http.routers.neo4j${PREFIX}metrics-secure.entrypoints=https_priv"
      - "traefik.http.routers.neo4j${PREFIX}metrics-secure.rule=Host(`${PREFIX}m.${TRAEFIK_HOST_VPC}`)"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
