neo4j:
  disableLookups: true
  neo4j:
    name: neo4jv5-internal
    resources:
      requests:
        cpu: 1000m
        memory: "2Gi"
      limits:
        cpu: 2000m
        memory: "2Gi"

    # Uncomment to set the initial password
    # password: "my-initial-password"
    passwordFromSecret: "neo4j-admin-auth"

    # Uncomment to use enterprise edition
    edition: "enterprise"
    acceptLicenseAgreement: "yes"
  config:
    dbms.security.oidc.azure.audience: 0d51e3f5-5053-4d39-81f2-a49ba2978e69
    dbms.security.oidc.azure.params: "client_id=0d51e3f5-5053-4d39-81f2-a49ba2978e69;response_type=code;scope=openid profile email"
    dbms.security.oidc.azure.authorization.group_to_role_mapping: |
      "86b0df6b-ec62-41f6-9250-d22e951755fa" = admin;

    # used to workaround lack of config in helm chart
    DATASETS: aml-2.0.1,dhs-2.0.1,crunchbase-2.0.0,fincrime-sales-2.0.1,insurance-fraud-2.0.0,lineage-2.0.0,online-lending-2.0.0,polegraph-2.0.1,unemployment-insurance-2.0.1
    DATASET_NEO4J_VERSION: 5.3.0

  podSpec:
    initContainers:
      - name: git-sync
        image: k8s.gcr.io/git-sync/git-sync:v3.6.2
        env:
        - name: GIT_SYNC_REPO
          value: https://github.com/Linkurious/docker-neo4j
        - name: GIT_SYNC_DEST
          value: docker-neo4j
        - name: GIT_SYNC_BRANCH
          value: develop
        - name: GIT_SYNC_ONE_TIME
          value: 'true'
        volumeMounts:
          - name: data
            mountPath: /tmp/git/
      - name: neo4j-restore
          # command: ['ls', '-lah', '/data/git-sync/', '&&', '/data/git-sync/docker-neo4j/scripts/dataset-download.sh']
        command: ['/data/docker-neo4j/scripts/dataset-download.sh', '-p', '/data']
        envFrom:
          - secretRef:
              name: neo4j-prod-nexus-dataset # imports NEXUS_TOKEN
        volumeMounts:
          - name: data
            mountPath: /data/
          - name: neo4j-conf
            mountPath: "/config/neo4j.conf"

