neo4j:

  config:
    # Devops, Engineering
    dbms.security.oidc.azure.authorization.group_to_role_mapping: |
      "85e901b9-1ac4-4cae-9f3c-a0a0840f5491" = admin; \
      "fc44e40f-bbe4-4d23-a0b7-2b543cc61240" = admin;

