apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neo4j-lke.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        {{- include "neo4j-lke.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: "neo4j:{{ .Chart.AppVersion }}"
          # command: ["/bin/sleep","{{default "100" .Values.sleepyTime}}"]
        command:
          - /bin/bash
          - -c
          - |
            set -e
            sleep 10
            IFS=',' read -ra DATASET <<< $DATASETS
            for dataset in "${DATASET[@]}"; do
              echo "Creating database ${dataset}"
              cypher-shell -a {{ .Release.Name }} -d 'system' -u 'neo4j'  -p ${NEO4J_AUTH#*/} "CREATE DATABASE \`${dataset}\` IF NOT EXISTS"
            done
        envFrom:
          - secretRef:
              # name: "{{ .Release.Name }}-auth"
              name: "neo4jv5-internal-auth"
          - configMapRef:
              name: "{{ .Release.Name }}-user-config"
